name: Auto Sync
on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Add remote URL
        run: |
          git remote add forked_repo https://soyyyyy:${{ secrets.DEPLOY_TOKEN }}@github.com/soyyyyy/36-SOPKATHON-WEB-WEB4
          git config user.name soyyyyy
          git config user.email da5868@naver.com

      - name: Push Changes to forked_repo
        run: |
          git push -f forked_repo main

      - name: Clean up
        run: |
          git remote remove forked_repo
